### ISSUE TITLE
Evaluation of generated data

### ISSUE THREAD

**Issue by SashiRin** [imoken1122/IDSGAN#2]
你好，我读了你们的文章，很有意思，想问一下，你们是如何判断生成的攻击数据是合法的呢？比如说，如果生成的是随机的噪声的话，IDS的检测率仍然会很低，因为本身的输入就不合法。谢谢。

English as follows:
I've read your paper, and found it is very interesting. But I have 1 question:
How do you ensure your generated attack valid? For example, if your generated data is just some random noise, the detection rate of IDS still will be low, because it is just invalid input of it. Thank you.

**Comment by imoken1122** [comment]
thanks for your questions. 
This is not a paper I wrote, so I don't know the details, but it may make sense to mention it.
However, when comparing generata models of "no_learn" and "learned" in generata_attacktraffic.py, I remember that the latter model had lower IDS accuracy than the former.
I think this model works, but don't take it too heavily as it was implemented for entertainment.

**Comment by SashiRin** [comment]
Thanks for your reply!
Actually, I'm doing the similar research now but find its not that easy. Generating something that can bypass IDS is easy but verifying it as a real attack pattern is not that trivial.

**Comment by niubifuwei** [comment]
> Thanks for your reply!
> Actually, I'm doing the similar research now but find its not that easy. Generating something that can bypass IDS is easy but verifying it as a real attack pattern is not that trivial.

仔细阅读文章后，你会发现文章的架构不会产生随机噪声，因为在设计网络的时候，41维数据中功能性特征没有改变，也就是说这些特征的存在使得这条连接具备攻击条件，至于GAN网络生成的部分是非功能性特征，不妨碍该条记录的攻击性质。提到输入合法，也就是该条连接是否具备攻击性质，事实上，功能性特征没有改变，因此合法。
只是如何保证功能性特征保持不变的具体操作没有说明，是在生成器中生成，还是先生成，然后再替换功能性特征。

**Comment by SashiRin** [comment]
> > Thanks for your reply!
> > Actually, I'm doing the similar research now but find its not that easy. Generating something that can bypass IDS is easy but verifying it as a real attack pattern is not that trivial.
> 
> 仔细阅读文章后，你会发现文章的架构不会产生随机噪声，因为在设计网络的时候，41维数据中功能性特征没有改变，也就是说这些特征的存在使得这条连接具备攻击条件，至于GAN网络生成的部分是非功能性特征，不妨碍该条记录的攻击性质。提到输入合法，也就是该条连接是否具备攻击性质，事实上，功能性特征没有改变，因此合法。
> 只是如何保证功能性特征保持不变的具体操作没有说明，是在生成器中生成，还是先生成，然后再替换功能性特征。

文章也是好久以前读的了，好多都记不清了。
但是他这篇文章感觉也是有好多没讲清楚。
他这个功能性特征的区分我觉得有点玄幻。如果功能性特征不变，非功能性特征变了，那是否说明非功能性特征也是作为特征被分类器所学习的。那么是不是就不能说它是非功能特征。还有如果说真的有非功能性特征，那么是不是不用上GAN，随机生成也是可以的？
还有就是如果也生成功能性特征，那么就是我的疑问，如果保证生成的样本实际有效？实际上，如果是为了生成对抗样本，我觉得他如果不做合法性的验证的话我觉得是有点说不通的。其实这也是GAN应用于其他领域所面临的一个痛点我觉得。毕竟对于多媒体数据来说，他们的特点是可以直接人来感知，来标注。但是对于网络数据，而且还只是没有内容的特征数据，想要做到这点不是太容易。。。

**Comment by niubifuwei** [comment]
请问您的邮箱多少，可以讨论一下这些问题，我也有这些问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Sashi"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月15日(星期一) 中午12:03
收件人:&nbsp;"imoken1122/IDSGAN"<IDSGAN@noreply.github.com&gt;;
抄送:&nbsp;"FW"<760345064@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [imoken1122/IDSGAN] Evaluation of generated data (#2)





   
Thanks for your reply!
 Actually, I'm doing the similar research now but find its not that easy. Generating something that can bypass IDS is easy but verifying it as a real attack pattern is not that trivial.
  
仔细阅读文章后，你会发现文章的架构不会产生随机噪声，因为在设计网络的时候，41维数据中功能性特征没有改变，也就是说这些特征的存在使得这条连接具备攻击条件，至于GAN网络生成的部分是非功能性特征，不妨碍该条记录的攻击性质。提到输入合法，也就是该条连接是否具备攻击性质，事实上，功能性特征没有改变，因此合法。
 只是如何保证功能性特征保持不变的具体操作没有说明，是在生成器中生成，还是先生成，然后再替换功能性特征。
  
文章也是好久以前读的了，好多都记不清了。
 但是他这篇文章感觉也是有好多没讲清楚。
 他这个功能性特征的区分我觉得有点玄幻。如果功能性特征不变，非功能性特征变了，那是否说明非功能性特征也是作为特征被分类器所学习的。那么是不是就不能说它是非功能特征。还有如果说真的有非功能性特征，那么是不是不用上GAN，随机生成也是可以的？
 还有就是如果也生成功能性特征，那么就是我的疑问，如果保证生成的样本实际有效？实际上，如果是为了生成对抗样本，我觉得他如果不做合法性的验证的话我觉得是有点说不通的。其实这也是GAN应用于其他领域所面临的一个痛点我觉得。毕竟对于多媒体数据来说，他们的特点是可以直接人来感知，来标注。但是对于网络数据，而且还只是没有内容的特征数据，想要做到这点不是太容易。。。

**Comment by SashiRin** [comment]
你现在应该可以看到我的profile下的邮箱。
